name: Publish Test PyPI Release

on:
  push:
    tags: ["*"]

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: publish-test-pypi
    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - uses: actions/setup-python@f677139bbe7f9c59b41e40162b753c062f5d49a3 # v5.2.0
        with:
          python-version: "3.11"

      - run: python -m pip install build
      - run: python -m build .

      - name: Publish to TestPyPI
        uses: pypa/gh-action-pypi-publish@8a08d616893759ef8e1aa1f2785787c0b97e20d6 # v1.10.0
        with:
          repository-url: https://test.pypi.org/legacy/
