name: update-pr-references
on:
  push:
    branches:
      - main

jobs:
  update_pr_numbers_in_change_fragments:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - uses: actions/setup-python@f677139bbe7f9c59b41e40162b753c062f5d49a3 # v5.2.0
        with:
          python-version: '3.x'
      - name: update any PR numbers in change fragments
        run: |
          python ./changelog.d/update-pr-refs.py
          if [ "$(git status --porcelain)" = "" ]; then
            echo "no changes"
          else
            git add changelog.d/
            git \
              -c user.name="GitHub Actions" \
              -c user.email="actions@github.com" \
              commit -m '(actions) update PR references'
            git push origin
          fi
